[package]
name = "ssri-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "0.15.1", features = ["ckb2023"] }
ckb-ssri = { path = "../../ckb-ssri" }
ckb-ssri-proc-macro = { path = "../../ckb-ssri-proc-macro" }
