[package]
name = "ckb_ssri_sdk"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ckb-hash = "0.116.1"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
ckb_ssri_sdk_proc_macro = { path = "../ckb_ssri_sdk_proc_macro" }
proc-macro2 = "1.0.87"
ckb-std = "0.15.3"
serde_molecule = "1.1.0"
serde = { version = "1.0.210", features = ["derive"] }