[package]
name = "pausable-udt"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "0.15.1", features = ["ckb2023"] }
ckb_ssri_sdk = { path = "../../ckb_ssri_sdk" }
serde_molecule = "1.1.0"
serde = { version = "1.0.210", features = ["derive"] }